version: '3'

services:
  firefox:
    container_name: elo7_fox
    restart: unless-stopped
    image: jlesage/firefox
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
      - elo7firefox:/config

